#!/usr/bin/with-contenv bash

# if not installed
[[ ! -e /config/MusicBee/MusicBee.exe ]] && \
    tar -xzf /install/musicbee_portable.tar.gz -C /config
    mv /install/musicbee.png /config/.local/share/icons/hicolor/256x256/apps
    mv /install/musicbee.desktop /config/.local/share/applications

# permissions
chown -R abc:abc \
    /config

# install winetricks
# su - abc -c "winetricks corefonts"

